--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: cartms
    version: v1
  name: cartms
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: cartms
      version: v1
  template: 
    metadata: 
      labels: 
        app: cartms
        version: v1

    spec: 

      containers: 
        - 
          image: "santanupaul/cartms:1"
          imagePullPolicy: Always
          name: cartms  
          env:
            - name: CartMS.configserverurl
              value: "http://configserver:8888"
            - name: CartMS.eureka.url
              value: "http://eureka:8761/eureka"  